### PR TITLE
Removing Costura

### PR DESCRIPTION
**Pull request by johnsimons**
Removing Costura as the language packas are not included and we don't really need it since SI is deployed via an installer

### CODE REVIEW

**Comment by johnsimons** [comment]
@gbiellem can you please update the installer to include all files under bin/release

**Comment by johnsimons** [comment]
@distantcam just to comfirm, we package all language subfolders right ? And the folder structure needs to stay intact ?
image

**Comment by distantcam** [comment]
@johnsimons That's correct, the folder structure needs to remain the same.

**Comment by johnsimons** [comment]
Tested installer, it work :)

@distantcam I think this is done, quick review ?

**Comment by distantcam** [comment]
This fixes #547

**Pull request merged**
