### PR TITLE
"Saga" is written as "Sage" in SagaId description

### PR DESCRIPTION
**Pull request by HEskandari**
@Particular/serviceinsight-maintainers please review again.

### CODE REVIEW

**Comment by adamralph** [comment]
Can we rebase the branch instead of merging from master? It will have to be reset to the commit before the merge and then rebased.

**Comment by HEskandari** [comment]
@adamralph this is rebased on top of other commits. See if it is good now.

**Comment by distantcam** [comment]
This change was originally just one line, but now there's other commits from other branches in this PR too. It's a bit of a mess. I think we should close this PR and redo it on a fresh branch.

**Comment by HEskandari** [comment]
yeah messed up for some reason, I'll send a cleaner PR.

**Pull request merged**
