### PR TITLE
[WIP] Export SequenceDiagram to image

### PR DESCRIPTION
**Pull request by johnsimons**
Task force: @weralabaj @johnsimons @HEskandari 

Related to: https://github.com/Particular/PlatformDevelopment/issues/286. Issue 286 has become Epic and may take a long time to resolve. This issue is to deliver short term benefit to users struggling with buggy-ness of the Sequence Diagram.

### Description

Exports a diagram to image.

See sample flow below (flow diagram included to visualize what percentage of the whole conversation is visible at once on SequenceDiagram):
example

The purpose of this task is to determine and implement the best solution to address this problem. The proposed approach is adding exporting to image functionality.

### Customer Communication
*Standard announcement and mention in a blog post on platform update.*

Until now you had to bring your manager to your screen to explain a fault. Now you can take your screen to your manager by using our new export as image function.

Our Customers have been asking for ways to take snapshots of the sequence diagram so they can distribute it easily to project stakeholders. We have implemented an easy way to export the diagram to an image.

### Impact Assessment

Seeing the whole diagram at once saves time and requires less mental to understand how the system works. This is especially important during **troubleshooting**, but is also useful during **implementation** or for **reviewing system runtime behaviour**.

Given that FlowDiagram works well even for large flows, customers are not likely to start using SequenceDiagram or keep using it. Instead they'll just stick to FlowDiagram. Therefore the overall impact is Medium.

### Alignment with Vision

Improves [Troubleshooting](https://github.com/Particular/Vision/issues/18) and [Coding](https://github.com/Particular/Vision/issues/20) experiences for [Developers](https://github.com/Particular/Vision/issues/15).

#### Implement
- [ ] Implement "export diagram to image" feature (preferred); export to PDF (print-friendly solution)
- [ ] or mplement full screen view

#### Document
- [ ] Send standard announcement
- [ ] Mention in a blog post (September platform update).
- [ ] Update current [SI overview](http://docs.particular.net/serviceinsight/getting-started-overview) -  add section on SequenceDiagram

#### Done
- [ ] Ready Customer Communications

Related to Particular/PlatformDevelopment#286

### CODE REVIEW

**Comment by weralabaj** [comment]
I think there's a risk that this prototype implementation won't work for SD vNext (depending on how it's implemented) so I'll put it off until the other one is completed.

**Comment by distantcam** [comment]
Closing this PR. When we're ready to do this work again we can open a new PR.

**Comment by adamralph** [comment]
Do we have an issue open representing this feature?

**Comment by HEskandari** [comment]
@adamralph Didn't find any. Issue #530 is related to export though.

**Comment by adamralph** [comment]
Thanks @HEskandari - raised #622 so that we have an open issue representing the feature.

**Pull request closed without merging**
