### PR TITLE
Added error handler for SD with raygun reporting

### PR DESCRIPTION
**Pull request by distantcam**
Fix for #545 

image

The link reports the exception + message headers to raygun.

### CODE REVIEW

**Comment by johnsimons** [comment]
@distantcam what is displayed after "... message data: " ?

**Comment by johnsimons** [comment]
Is that an error message ?

**Comment by johnsimons** [comment]
Are we showing the user exactly what data we are sending to us ?

**Comment by distantcam** [comment]
@johnsimons Yes that's the exception message.

No we are not showing what data is being sent to us. Do we need to?

**Comment by johnsimons** [comment]
@distantcam so won't that message always be the same ?

**Comment by distantcam** [comment]
@johnsimons Nope

**Comment by johnsimons** [comment]
@distantcam 

> No we are not showing what data is being sent to us. Do we need to?

What is your gut feeling ? Would u press that button without knowing exactly what is being sent ? Also do we have user contact details if we need more info ?

**Comment by johnsimons** [comment]
@distantcam can u give me some examples of what the message is ?

**Comment by distantcam** [comment]
@johnsimons 

> What is your gut feeling ? Would u press that button without knowing exactly what is being sent ? Also do we have user contact details if we need more info ?

It's the same as the exception report dialog, plus the headers of the message. I'd press the button, and if I was concerned I'd watch the packet with fiddler first.

> can u give me some examples of what the message is ?

So far we have 
- Only one arrow is allowed to come in
- The given key was not present in the dictionary.

**Comment by johnsimons** [comment]
> It's the same as the exception report dialo

pretty sure @gbiellem raised an issue to fix this, so we do give the option for the user to see the data that we are about to send. @gbiellem do u remember this ?

**Comment by johnsimons** [comment]
> The given key was not present in the dictionary.

That is not a very nice thing to display to the user.

How about all we say is:
There was a problem parsing the data to display the diagram.
Click here ....

**Comment by distantcam** [comment]
> That is not a very nice thing to display to the user.

I agree, but some users have a bad habit of screenshotting the error message and sending that instead of the nice fancy report error button. At least this way we'll have something. :/

**Comment by johnsimons** [comment]
@distantcam if a user reports a screenshot, that is IMO a good thing, because hopefully we can contact them and ask more questions.
So I do think that displaying a generic message to the user is in this scenario a better option

**Comment by johnsimons** [comment]
BTW, that is what we have decided previously, see https://github.com/Particular/ServiceInsight/issues/545#issuecomment-168962919

**Comment by distantcam** [comment]
I'm happy to change the message to a more generic one, but I would like to keep the report error feature as this will cover other errors the diagram might have, not just #545

**Comment by johnsimons** [comment]
Yes of course, see https://github.com/Particular/ServiceInsight/issues/545#issuecomment-169159023

**Comment by distantcam** [comment]
Well I had read #545 prior to creating this PR. ;)

**Comment by HEskandari** [comment]
Would have been good to return a 'ticket number' to the client, so that they can follow up the issue with us using that...maybe we could generate a GUID (or some sort of a unique-hash of the report) and give it back to the client while including that in the report?

**Pull request merged**
