### PR TITLE
[WIP] Added expand window to show all message data

### PR DESCRIPTION
**Pull request by johnsimons**
This PR addresses issue raised in #320 

An icon is now displayed in the top right corner that allows the user to expand the view to see the body on the message, see 
image

Here is the view once the user clicks on the icon:
image

and no icon is displayed if message has no body:
image

It will hopefully also address #301

### CODE REVIEW

**Comment by johnsimons** [comment]
@dannycohen @sergioc please comment whether this is an appropriate solution or not ?

**Comment by dannycohen** [comment]
@johnsimons - Seems like both icons (expanded / collapsed) are the same.

**Comment by johnsimons** [comment]
This is the latest design for improvements:
saga-view

**Comment by HEskandari** [comment]
Is this PR still a WIP? It's been idle for some time.

**Comment by johnsimons** [comment]
Yes, it has.
Want to have a loot at it, and see what u think ?

**Comment by distantcam** [comment]
I'm going to close this PR because it will take some work to bring it up to date. Once we're ready to try again we can do a new PR.

**Comment by adamralph** [comment]
Do we have an open issue representing this bug?

**Comment by johnsimons** [comment]
@adamralph  no, but you can pick my brain about it, setup a call?

**Comment by adamralph** [comment]
@johnsimons it looks #320 is the nearest thing we have, so I'll reopen that, so that we have an open bug to triage. We can update the issue with anything in this PR which it doesn't already capture.

**Pull request closed without merging**
