### PR TITLE
License Agreement Update

### LINKED ISSUE #635: Update License agreement in the installer.
Related to https://github.com/Particular/NServiceBus/pull/4280, we are working to change the license agreement and privacy policy to be compliant. 

Once we have the right text, SI Installer will need to reflect that.

cc / @kbaley

### LINKED ISSUE #676: ServiceInsight Installer is missing the license dialog screen
This license acceptance screen is not  shown on install like the other platform installers.

### PR DESCRIPTION
**Pull request by gbiellem**
Relates to #635 
Latest revision of  the License Agreement  

@HEskandari  as discussed

---

Fixes #635
Fixes #676

### CODE REVIEW

**Comment by HEskandari** [comment]
I have checked the formatting and it LGTM. I haven't verified all the text though.

**Comment by adamralph** [comment]
@gbiellem @Particular/serviceinsight-maintainers I'm confused.

I've performed a search of file contents and I can't find a single reference to `License.rtf` across the entire solution. Are we sure it's required here?

**Comment by gbiellem** [comment]
@adamralph Actually you've found a bug. The SI installer is missing the license agreement screen.
Issue raised #676.  I fix it is  and add it to this PR




  and show this license on install.  I can correct that.  Do you want that as part of this PR or seperately?

**Comment by HEskandari** [comment]
@gbiellem Tested the artefact of the latest commit. The license dialog now shows up when I run the installer.

**Comment by HEskandari** [comment]
@Particular/serviceinsight-maintainers This is awaiting a second approval.

**Comment by adamralph** [comment]
I'm on it.

**Comment by HEskandari** [comment]
@adamralph have you tried marking rtf files as text? I've had text with unicode characters picked on by git which would go away if you mark them as text. See if [this](http://stackoverflow.com/questions/13486027/how-can-i-treat-a-file-not-a-binary-git) helps?

**Comment by adamralph** [comment]
Thanks @HEskandari, altering the `.gitattributes` file to treat RTF as text did the trick.

**Comment by gbiellem** [comment]
@HEskandari  @adamralph  I've fixed up the numbering and tweaked the indentation to be consisent and  not as big so it fits better in the dialog.  Please review

**Comment by gbiellem** [comment]
@indualagarsamy  ☝️  FYI

**Comment by adamralph** [comment]
Thanks @gbiellem

**Pull request merged**
