### PR TITLE
Feedback button

### LINKED ISSUE #538: User feedback widget/mechanism
Add some sort of mechanism for users to provide feedback in-app. Possibly automatically convert feedback into GH issues automatically.

### PR DESCRIPTION
**Pull request by HEskandari**
Resolves #538

### CODE REVIEW

**Comment by HEskandari** [comment]
@Scooletz this too can be reviewed. The reason I've marked it as WIP was it can use some minor tweaks to the UI if we have time before the release. It won't impact the functionality though.

**Comment by Scooletz** [comment]
Too much WPF for me. I cannot confirm that it solves the issue nor that is implemented according to repo standards.

**Comment by HEskandari** [comment]
@Scooletz Can jump on a call and review the code with you?

**Comment by HEskandari** [comment]
@seanfarmar this is updated and is ready for the review.

**Review by seanfarmar — APPROVED** [review]
LGTM reviewed with @HEskandari

**Pull request merged**
