### PR TITLE
Add install info for SagaAudit v6

### PR DESCRIPTION
**Pull request by boblangley**
Connects to https://github.com/Particular/PlatformDevelopment/issues/677

### CODE REVIEW

**Comment by HEskandari** [comment]
@boblangley do we need to display the message for both v5 and v6? Could we simplify the message and copy the right command (on CopyCommand) based on the version?

**Comment by boblangley** [comment]
@HEskandari  We display the message for both v4 and v5 so I just assumed we would do the same for v6. If we want to handle this differently I am not opposed.

**Comment by HEskandari** [comment]
This is what I'm proposing:

image

What do you think @distantcam?

Do you mind if I update the PR (if/once/when this is approved)?

**Comment by boblangley** [comment]
Not at all.

**Comment by HEskandari** [comment]
@boblangley what's your thoughts on the proposed change?

**Comment by boblangley** [comment]
I am all for it and appreciate the help.

**Comment by distantcam** [comment]
I don't like having a generic `x` there. Could we have the text update the appropriate version based on the selected message?

**Comment by HEskandari** [comment]
@distantcam Don't think there'd be any issues with that. That'd actually be even better.

**Comment by HEskandari** [comment]
@boblangley @distantcam Please review.

**Comment by boblangley** [comment]
@HEskandari Looks good to me. I ran the v6 SagaAudit plugin smoke test sending the control messages to the wrong queue. The Saga tab works as expected. :+1:

**Comment by boblangley** [comment]
Should we have a fallback if the version header is missing or unparseable? Are we confident about the version information being in the headers?

**Comment by HEskandari** [comment]
@boblangley AFAIK version has been there for quite some time. Think @johnsimons might be able to confirm?

**Comment by johnsimons** [comment]
Yes version has been there since the beggining

**Comment by HEskandari** [comment]
@boblangley Merged. Do we need to get a release out as a part of v6 launch or prior?

**Comment by boblangley** [comment]
I think as part of is good enough.

**Comment by HEskandari** [comment]
Is there a separate task/item to track the release? Should we close this issue?

**Comment by boblangley** [comment]
Yes let's close the pr. We can track the release to support v6 in another issue for a later stage. Unless of course we end up doing a Service Insight release in the meantime.

**Pull request merged**
