### PR TITLE
Improved design for SequenceDiagram

### PR DESCRIPTION
**Pull request by johnsimons**
Milestone: https://github.com/Particular/ServiceInsight/milestones/Sequence%20Diagram%20vNext

Task force: @sergioc @petersgiles @distantcam @johnsimons @HEskandari 

### Description

Related to: https://github.com/Particular/PlatformDevelopment/issues/286. Issue 286 has become Epic and may take a long time to resolve. This issue is to deliver short term benefit to users struggling with buggy-ness of the Sequence Diagram.

Make handler boxes height adequate to the number of messages that are sent by this handler.
Adjust the shape of the connector lines accordingly.

untitled

### Customer Communication
Standard announcement, mention in a blog post on platform update.

This addresses issues with:
- overlapping arrows
- not adhering to UML standards
- confusing and difficult to understand flow representation 

### Impact Assessment

Based on comparison between mocks of new design and current design for a few selected flow, we decided that the new design is cleaner and requires less mental effort to understand what the diagram visualizes. This is especially important during **troubleshooting**, but is also useful during **implementation** or for **reviewing system runtime behaviour**.

Given that FlowDiagram works well for the tasks mentioned above, customers are not likely to start using SequenceDiagram or keep using it. Instead they'll just stick to FlowDiagram. Therefore the overall impact is Medium.

### Alignment with Vision

Improves [Troubleshooting](https://github.com/Particular/Vision/issues/18) and [Coding](https://github.com/Particular/Vision/issues/20) experiences for [Developers](https://github.com/Particular/Vision/issues/15).

#### Implement
- [x] Adjust the shape of the connector lines
- [x] Make height of the boxes representing handlers relative to the number of outgoing messages
- [x] Verify for selected flows from customer databases

#### Document
- [ ] Send standard announcement
- [ ] Mention in a blog post (September platform update).
- [x] Update current [SI overview](http://docs.particular.net/serviceinsight/getting-started-overview) -  add section on SequenceDiagram

#### Done
- [ ] Ready Customer Communications

Task for Particular/PlatformDevelopment#286

### CODE REVIEW

**Comment by sergioc** [comment]
@johnsimons taking into account the following scenario we discussed:

screenshot 2015-09-17 08 47 09

The following questions arose regarding how to visualize:

1. endpoint send msg to self
2. timeouts
3. message labels next to connector arrows for all msgs
4. linkage between msg and processing handlers

All of the following visuals demonstrate the same solution for 1. and 2.

**Option A)** The following shows 
- all msg labels placed consistently above the beginning point of the connector arrows, except for timeout and send to self. 
- handlers not connected directly to msg, but are labeled. 
- the handler label could be toggled on and off, since it is also available in the handler tooltip.

serviceinsight sequence diagram 497 _05 message hovered copy 12


**Option B)** The following shows:  
- all msg labels next to end of connector arrows. 
- handlers not connected directly to msg, but are labeled
- the handler label could be toggled on and off, since it is also available in the handler tooltip.

serviceinsight sequence diagram 497 _05 message hovered copy 13


**Option C)** The following shows: 
- all msg labels placed consistently above the beginning point of the connector arrows, except for timeout and send to self. 
- handlers connected directly to msgs. If processed after other msgs were sent in meanwhile, add another connection along endpoint spine.
- endpoint spine widens dynamically to allow multiple disjointed handlers to be connected in parallel

serviceinsight sequence diagram 497 _05 message hovered copy 14

**Comment by sergioc** [comment]
Note - I updated the previous comment a couple of times to fix some inaccuracies, make sure you check the latest version of the comment in GH.

**Comment by johnsimons** [comment]
Things left to do:
- [ ] Sticky header
- [ ] Hovering to correlate enqueue and handler
- [ ] Animation to correlate enqueue and handler, discussed with @distantcam, a running arrow
- [ ] Action menu not working, the action items are disabled, discussed with @distantcam 
- [ ] Display saga header in handler (not sure how yet)
- [ ] Remove selection from canvas elements

**Comment by johnsimons** [comment]
Failed handler look and feel:
image

//cc @sergioc

**Comment by sergioc** [comment]
@johnsimons that failed handler representation has 2 issues that prevent it from being easily spotted: 

- the red stroke is too thing and will be too inconspicuous in the middle of more info.
- the red stroke does not contrast sufficiently with the grey handler color.

Here's an updated version that solves the above 2 issues, with an icon inside to help minimize reliance on color alone:

screenshot 2015-09-29 15 13 26

Link to icon: https://www.dropbox.com/s/efl5rqg2olx7ngq/failed.svg?dl=0

**Comment by HEskandari** [comment]
@sergioc @johnsimons I've incorporated the failed handler style.

**Comment by johnsimons** [comment]
@HEskandari where we up to on this one? Is the todo list up to date ?

**Comment by johnsimons** [comment]
Use a split dropdown menu instead of context menu
image

Render borders on hover

**Comment by johnsimons** [comment]
Add label for handler eg, IHandle blah message

**Comment by HEskandari** [comment]
The chosen scenario drawn by the new version of SequenceDiagram in SI would look like this:

sequencediagramscenario

**Comment by HEskandari** [comment]
Things left to do as an aftermath of the demo session and the latest discussions:

- [ ] Positioning of the dropdown to the center
- [ ] Fixing the reloading when the grid selection is cleared
- [ ] Changing the endpoint to something that doesn't have any message should clear the diagram.
- [ ] On mouse hover on the ellipsis button, change the image to reflect that can be clicked
- [ ] Underline the message name text on mouse hover
- [ ] Display hand mouse pointer on mouse hover
- [ ] Display the blue line/arrows when clicking the related handler box or the message. Remove the display on hovering.
- [ ] Put a label beside the handler box to display the message name + icon. The label goes to the opposite direction of the first arrow that comes out of the processing box. The first box, does not require a label (start a of conversation).
- [ ] Sticky headers for the diagram.
- [ ] Changing styling of the message box when the message has failed (handler box is red). Waiting for Sergio to provide guidance.
- [ ] Changing the style of the ellipsis button when the message is not selected and context menu is open

**Comment by sergioc** [comment]
> Display hand mouse pointer on mouse hover

@HEskandari hover on what and what's the goal of showing the hand pointer?

**Comment by johnsimons** [comment]
@sergioc I am concerned that it is not obvious that the message can be selected, so we are just copying the same behaviour that the flow diagram already has.

**Comment by sergioc** [comment]
> @sergioc I am concerned that it is not obvious that the message can be selected, so we are just copying the same behaviour that the flow diagram already has.

Hand pointer cursor is not used to convey something can be selected. Let's validate your concern with user testing before releasing and if necessary, iterate after that. Let's discuss on the next call.

**Comment by johnsimons** [comment]
ok lets do that @sergioc

**Comment by petersgiles** [comment]
I'm removing myself from the task force for now since I'm currently in no position to commit any time to it.
If and when a task force lead is assigned and the issue is being driven forward, please feel free to ping me if you feel I can be of value and/or you'd like me to be a task force member.

**Comment by distantcam** [comment]
This PR is effectively a duplicate of the platform dev card and there's no point keeping both open.

Closing this a duplicate.

**Comment by johnsimons** [comment]
So we not merging it ?
IMO if you want to close an issue, close the one in plat dev, not this one.

On Tue, 24 Nov 2015 at 19:48 Cameron MacFarland <notifications@github.com>
wrote:

> This PR is effectively a duplicate of the platform dev card and there's no
> point keeping both open.
>
> Closing this a duplicate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceInsight/pull/497#issuecomment-159211220>
> .
>
-- 

*John Simons*
*Engineer, Particular Software*

Email*:*  john.simons@particular.net
Web:    www.particular.net

**Comment by petersgiles** [comment]
@distantcam I think if we're doing some house-keeping (and I agree that something should probably be cleaned up) we really should ensure everything is merged properly and the task-force is across the change first.

**Comment by HEskandari** [comment]
I'm with @johnsimons on this one. The plat dev one is the one with all the obsolete bug reports that is no longer relevant.

**Comment by johnsimons** [comment]
Ok, lets fix this

**Comment by distantcam** [comment]
Ok I'll close the platform dev issue and put this PR on the board.

**Comment by mikeminutillo** [comment]
Points from meeting with @sergioc to discuss user testing:
- @sergioc will identify some champs who will not be attending NSBCon to be involved
- The user tests will occur sometime during the next week (Nov 29th-Dec 3rd)
- @sergioc will come up with some high-level data requirements for the tests and the task force will produce some data to match
- We will also release a beta to attendees of NSBCon and encourage feedback

@sergioc did I miss any major action items?

**Comment by sergioc** [comment]
@mikeminutillo you got it.

**Comment by sergioc** [comment]
one thing we didn't discuss @mikeminutillo : I'll process the test results for discussion on Dec. 8th or 9th. From there we'll decide together whether there's any show stoppers.

**Comment by HEskandari** [comment]
There's no outstanding issue left for development. We're waiting for @sergioc to do a round of user testing tomorrow to make sure that we haven't missed anything (as we think we haven't) and this is good for release on *Monday*, pending nothing major comes out of the user testing session.

As for customer communication, we're thinking to put together a blog post or maybe a quick video to demo this feature upon release.

**Pull request merged**
